### ISSUE TITLE
句子迷的反爬虫如何处理的？

### ISSUE THREAD

**Issue by Jaccorot** [longxiaofei/juzimi#1]
Hi，最近我也在爬句子迷，动态UA，禁cookie，加间隔都用上了，但还是被屏蔽了，想请教一下你这边是如何反反爬虫的？

**Comment by longxiaofei** [comment]
之前没有看Issues的习惯，一年过去了。。。
这个网站会Ban你ip的，一、慢点爬   二、用代理ip

**Comment by Jaccorot** [comment]
谢谢，陆陆续续爬完了，总的原则就是慢着来，还是万分感谢
