### ISSUE TITLE
请问一下句子迷的数据可以共享一下吗？

### ISSUE THREAD

**Issue by einverne** [longxiaofei/juzimi#2]
今天登录juzimi 突然发现网站“关闭了” 说 

句子迷因技术升级，暂时停止访问。

想想之前收藏的内容全部看不到了，我看到您之前曾经爬取过一部分，不知道您愿不愿意分享一下。

**Comment by longxiaofei** [comment]
> 今天登录juzimi 突然发现网站“关闭了” 说
> 
> 句子迷因技术升级，暂时停止访问。
> 
> 想想之前收藏的内容全部看不到了，我看到您之前曾经爬取过一部分，不知道您愿不愿意分享一下。

由于是二年前爬的了，我也没有之前的数据了，抱歉

**Comment by einverne** [comment]
嗯好的，那个感谢您的回复。我从Cache 中找回了15万条数据，放在了[这里](https://book.einverne.info/juzi/list)
